name: Deploy packages
on:
  push:
    branches: [main]
env:
  DEBIAN_FRONTEND: 'noninteractive'
  WASABI_BUCKET: 'server-packages.hunterwittenborn.com'

jobs:
  deploy:
    name: Deploy Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup makedeb and Prebuilt-MPR APT repositories
        uses: makedeb/setup-makedeb@main
        with:
          pbmpr-repo: true
      - name: Install rclone
        run: sudo apt-get install rclone -y
      - name: Set up rclone config
        run: |
          rclone config create wasabi s3 \
          provider='Wasabi' \
          access_key_id="${{ secrets.WASABI_ACCESS_KEY_ID }}" \
          secret_access_key="${{ secrets.WASABI_ACCESS_KEY_SECRET }}" \
          endpoint='s3.wasabisys.com'
      - name: Clone packages from Prebuilt-MPR
        run: |
          cd ../
          mkdir debs/
          mapfile -t packages < <(cat server-packages/prebuilt-mpr-pkgs.txt)

          for pkg in "${packages[@]}"; do
            pkgname="$(echo "${pkg}" | sed 's|=.*||')"
            version="$(echo "${pkg}" | sed 's|.*=||')"

            apt-get download "${pkgname}=${version}"
            mv "${pkgname}_${version}_amd64.deb" debs/
          done
      - name: Build custom packages
        run: |
          cd pkgs/
          for pkg in *; do
            cd "${pkg}"
            makedeb -s --no-confirm --pass-env
            cp *.deb ../../../debs/
            cd ../
          done
      - name: Set up APT repository
        run : |
          cd ../debs
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
      - name: Purge S3 content
        run: |
          mapfile -t path < <(rclone lsf "wasabi:${WASABI_BUCKET}")

          for path in "${path[@]}"; do
            rclone purge "wasabi:${WASABI_BUCKET}/${path}"
          done
      - name: Upload new APT repository directory
        run: rclone copy -v ../debs "wasabi:${WASABI_BUCKET}/apt"