name: Deploy packages
on:
  push:
    branches: [main]
env:
  DEBIAN_FRONTEND: 'noninteractive'
  WASABI_BUCKET: 'server-packages.hunterwittenborn.com'
  WASABI_ENDPOINT: 's3.wasabisys.com'

jobs:
  deploy:
    name: Deploy Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup makedeb and Prebuilt-MPR APT repositories
        uses: makedeb/setup-makedeb@main
        with:
          pbmpr-repo: true
      - name: Install needed packages
        run: sudo apt-get install aptly rclone -y
      - name: Set up rclone config
        run: |
          rclone config create wasabi s3 \
          provider='Wasabi' \
          access_key_id="${{ secrets.WASABI_ACCESS_KEY_ID }}" \
          secret_access_key="${{ secrets.WASABI_ACCESS_KEY_SECRET }}" \
          endpoint="${WASABI_ENDPOINT}"
      - name: Set up aptly config
        run: |
          echo "{
            \"S3PublishEndpoints\": {
              \"server-packages\": {
                \"region\": \"us-east-1\",
                \"bucket\": \"${WASABI_BUCKET}\",
                \"endpoint\": \"${WASABI_ENDPOINT}\",
                \"awsAccessKeyID\": \"${{ secrets.WASABI_ACCESS_KEY_ID }}\",
                \"awsSecretAccessKey\": \"${{ secrets.WASABI_ACCESS_KEY_SECRET }}\"
              }
            }
          }" > ~/.aptly.conf
      - name: Set up aptly repo
        run: aptly repo create -distribution=jammy -component=main server-packages
      - name: Add packages from Prebuilt-MPR
        run: |
          cd ../
          mkdir debs/
          mapfile -t packages < <(cat server-packages/prebuilt-mpr-pkgs.txt)

          for pkg in "${packages[@]}"; do
            pkgname="$(echo "${pkg}" | sed 's|=.*||')"
            version="$(echo "${pkg}" | sed 's|.*=||')"

            apt-get download "${pkgname}=${version}"
            aptly repo add server-packages "${pkgname}_${version}_amd64.deb"
          done
      - name: Purge S3 content
        run: rclone purge "wasabi:${WASABI_BUCKET}/apt"
      - name: Upload new APT repository
        run: aptly publish repo -distribution=jammy -component=main -skip-signing server-packages 's3:server-packages:apt'
