name: Deploy packages
on: push
env:
  WASABI_BUCKET: 'server-packages.hunterwittenborn.com'
jobs:
  deploy:
    name: Deploy Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: server-packages
      - name: Set up Prebuilt-MPR APT repository
        uses: makedeb/setup-makedeb@main
        with:
          makedeb-repo: false
          pbmpr-repo: true
      - name: Install rclone
        run: sudo apt-get install rclone -y
      - name: Set up rclone config
        run: |
          rclone config create wasabi s3 \
          provider='Wasabi' \
          access_key_id="${{ secrets.WASABI_ACCESS_KEY_ID }}" \
          secret_access_key="${{ secrets.WASABI_ACCESS_KEY_SECRET }}" \
          endpoint='s3.wasabisys.com'
      - name: Download packages from Prebuilt-MPR
        run: |
          mkdir -p apt/debs/
          mapfile -t packages < <(cat server-packages/packages.txt)

          for pkg in "${packages[@]}"; do
            pkgname="$(echo "${pkg}" | sed 's|=.*||')"
            version="$(echo "${pkg}" | sed 's|.*=||')"

            apt-get download "${pkgname}=${version}"
            mv "${pkgname}_${version}_amd64.deb" apt/debs/
          done
      - name: Prepare APT repository directory
        run: |
          cd apt/
          dpkg-scanpackages --multiversion debs/ > Packages
          gzip -k -f Packages
          apt-ftparchive release debs/ > Release
          cd ../
      - name: Purge S3 content
        run: |
          mapfile -t path < <(rclone lsf "wasabi:${WASABI_BUCKET}")

          for path in "${path[@]}"; do
            rclone purge "wasabi:${WASABI_BUCKET}/${path}"
          done
      - name: Upload new APT repository directory
        run: rclone copy -v ./apt "wasabi:${WASABI_BUCKET}/apt"
