name: Deploy packages
on: {"push", "pull_request"}
env: {"DEBIAN_FRONTEND": "noninteractive"}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Prebuilt-MPR APT repository
        run: |
          curl -q 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
          echo "deb [signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr focal" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
          sudo apt update

      - name: Clone 'server-packages' repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone packages from Prebuilt-MPR
        run: |
          cd ../
          mkdir debs/
          mapfile -t packages < <(cat server-packages/packages.txt)

          for pkg in "${packages[@]}"; do
            pkgname="$(echo "${pkg}" | sed 's|=.*||')"
            version="$(echo "${pkg}" | sed 's|.*=||')"

            apt-get download "${pkgname}=${version}"
            mv "${pkgname}_${version}_amd64.deb" debs/
          done

      - name: Deploy packages
        run : |
          git restore ./
          git checkout deploy
          rm * -rf
          
          cp ../debs/* ./
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./
          git commit -m "Updated packages"
          git push
