name: Deploy packages
on:
  push:
    branches: [main]
env: {"DEBIAN_FRONTEND": "noninteractive"}
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone 'server-packages' repository
        uses: actions/checkout@v3
      - name: Setup Prebuilt-MPR APT repository
        uses: makedeb/setup-makedeb@main
        with:
          pbmpr-repo: true
      - name: Clone packages from Prebuilt-MPR
        run: |
          cd ../
          mkdir debs/
          mapfile -t packages < <(cat server-packages/packages.txt)

          for pkg in "${packages[@]}"; do
            pkgname="$(echo "${pkg}" | sed 's|=.*||')"
            version="$(echo "${pkg}" | sed 's|.*=||')"

            apt-get download "${pkgname}=${version}"
            mv "${pkgname}_${version}_amd64.deb" debs/
          done
      - name: Set up APT repository
        run : |
          cd ../debs
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ../debs
      - name: Deploy site
        uses: actions/deploy-pages@v1
